# Generated by Django 4.1.7 on 2023-03-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_description_job_experience_job_job_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salaey',
            new_name='salay',
        ),
    ]
