# Generated by Django 4.1.7 on 2023-03-30 02:47

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('website', models.URLField(max_length=60)),
                ('cv', models.FileField(upload_to=job.models.cv_upload)),
                ('cover_letter', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
